### PR TITLE
Fix: Select All Similar in Range (Spanners)

### LINKED ISSUE #984: Select Pedal lines in a range does not work.
Add Pedal to some bars. Select a range, right-click a Pedal line, and then "Select similar elements in range selection". Result: Nothing is selected. " Works as expected in 3.6.2
Version 3.7.0.16362252962 

[Pedal.zip](https://github.com/user-attachments/files/21375827/Pedal.zip)

### PR DESCRIPTION
**Pull request by worldwideweary**
Resolves: #984

### CODE REVIEW

File: libmscore/score.cpp [hunk 1]
```diff
@@ -1880,6 +1880,10 @@ void Score::scanElementsInRange(void* data, void (*func)(void*, Element*), bool
                         ss->scanElements(data, func, all);
                         }
                   }
+            else if (e->isSpannerSegment()) {
+                  const auto ss = toSpannerSegment(e);
+                  ss->scanElements(data, func, all);
+                  }
```
Comment (Jojo-Schmitz) [inline libmscore/score.cpp:1886]: See corresponding code in master, https://github.com/musescore/MuseScore/blob/e9880db635f7f13a90e33f171f4b21a8a56b395c/src/engraving/dom/score.cpp#L2060-L2071

Comment (worldwideweary) [reply libmscore/score.cpp:1886]: Using a set like that doesn't make much sense to me. Does it to you? If so please explain. Almost seems like an extra unnecessary step.

Comment (Jojo-Schmitz) [reply libmscore/score.cpp:1886]: No idea really, but seems needed on order to process spanners in the right order?

Comment (worldwideweary) [reply libmscore/score.cpp:1886]: It's still within the loop though and only acts on the most recently added spanner. Doesn't make any sense!
Plus it almost seems superfluous to go through all the segments. Continued segments already are included via range selection from what I can tell

image


For example that blue shows the range selection, yet the "continued" slur is selected there and so included with the filtering

but again... i suppose sticking with the same code for backporting purposes is the main idea

Comment (Jojo-Schmitz) [reply libmscore/score.cpp:1886]: > but again... i suppose sticking with the same code for backporting purposes is the main idea

Yers, it is. Not sure though whether it is feasible here, that `insert()` seems to be C++17, not sure we can rely in this being avialble for all current platforms and builds?

Comment (worldwideweary) [reply libmscore/score.cpp:1886]: I'll try it and do a force push to see if it goes through and see what the conveyor says

Comment (Jojo-Schmitz) [reply libmscore/score.cpp:1886]: Would this work?
```cpp
      for (Element* e : _selection.elements()) {
            if (!e->isSpannerSegment())
                  continue;
            Spanner* spanner = toSpannerSegment(e)->spanner();
            for (SpannerSegment* ss : spanner->spannerSegments()) {
                  ss->scanElements(data, func, all);
                  }
            }
```

Comment (worldwideweary) [reply libmscore/score.cpp:1882]: It's not really any different than what I was doing though initially though, save for using a continue instead of an if-clause. Quite literally the same thing.
