### PR TITLE
[Interaction] Fix: Playback keeps constraint of borders like while na…

### LINKED ISSUE #376: Updating view during playback loses centering
Especially prevalent when "Limit scroll area to page borders". 

Scroll wheel updates to "re-center" yet playback updating resets the view to TOP-LEFT. Demonstration:

https://github.com/Jojo-Schmitz/MuseScore/assets/7139517/40b9df25-20dd-46f5-9448-a0bde737694b

It looks like Mu4 some how fixed this sometime... 
The shakiness is when scroll-wheeling update fighting with the "playback cursor" updating. . .

### PR DESCRIPTION
**Pull request by worldwideweary**
Resolves: #376

Came across this problem when doing some things on personal build. 
If you find the time, please test this. Seems to work well over here.. Results are then like:

https://github.com/Jojo-Schmitz/MuseScore/assets/7139517/f21d8597-993b-46ff-9468-767b3ae6d04b

### CODE REVIEW

File: mscore/scoreview.cpp [hunk 1]
```diff
@@ -3853,7 +3853,13 @@ void ScoreView::adjustCanvasPosition(const Element* el, bool playBack, int staff
       if (oldX == x && oldY == y)
             return;
 
-      setOffset(-x * physicalZoomLevel(), -y * physicalZoomLevel());
+      int cx = 0, cy = 0;
+      constraintCanvas(&cx, &cy);
+      x *= -physicalZoomLevel();
+      y *= -physicalZoomLevel();
+      cx = (x < 0) ? x : cx + _matrix.dx();
```
Comment (Jojo-Schmitz) [inline mscore/scoreview.cpp:3860]: Any special reason not to calculate and use the y offset too? Like for horizontal scrolling?

Comment (worldwideweary) [reply mscore/scoreview.cpp:3860]: Y'know, I didn't really think about the y-constraint since I was mainly concerned with the limiting of the horizontal borders in page mode and vertical scrolling. Not sure if there'd be any negative repercussions by trying the equivalent (but guessing *probably* not):

```cpp
cy = (y < 0) ? y : cy + _matrix.dy();
setOffset(cx, cy);
```

I'll check it out later

Comment (Jojo-Schmitz) [reply mscore/scoreview.cpp:3860]: Dunno ;-)

Comment (worldwideweary) [reply mscore/scoreview.cpp:3860]: Fwiw, I don't recall experiencing an issue with y-constraints, but I usually use vertical scrolling and limit scroll area options, so not sure if there's anything to be fixed... ;)

Comment (Jojo-Schmitz) [reply mscore/scoreview.cpp:3860]: Let's put it this way: in master there's `emit offsetChanged(_matrix.dx(), _matrix.dy());`, in 2 places, so both get updated?
