### PR TITLE
Fix GH#359: Crash on Voice2-4 expanding into new measure

### LINKED ISSUE #359: Shortcut to increase note or rest duration beyond the measure causes instant crash
A bug, not present in previous versions, was somehow introduced in recent buildings of MU3.7.
In other versions, if we select the last note or rest of a measure and press the keyboard shortcut of a longer duration, automatically the same note is generated tied in the next measure.
Example: Suppose in a 4/4 measure we have two half notes, C and D. If we select D and press 7 (shortcut to whole note) automatically another half note D appears in the next measure and already tied to the D at the previous measure.
Now, at the latest appimage builds of MU3.7, whenever I try to do this the program crashes.
It was tested in an up-to-date Kubuntu 23.10 using the appimage version from the latest builds of MU3.7. The bug occurs with both, notes and rests.

### PR DESCRIPTION
**Pull request by worldwideweary**
Resolves: #359 
Instead of only reverting the change, I tried to get the same "intention" as the 4.x branch by way of seeing if the resulting "total fraction" was going to spill over into the next measure. If so, then perform the expand function (it was crashing because 3.x apparently needs to expand there when extending past current measure). Putting it back in how it was would cause unnecessary rests though every time. Test please if you're willing... 

I have a screen cast showing how it doesn't make a voice-2 rest for no reason and also that it doesn't crash on my side over here if it "spills over".

https://github.com/Jojo-Schmitz/MuseScore/assets/7139517/20f3013e-a1df-439c-8844-c8fc97051ad1

### CODE REVIEW

File: libmscore/cmd.cpp [hunk 1]
```diff
@@ -1386,6 +1388,13 @@ void Score::changeCRlen(ChordRest* cr, const Fraction& dstF, bool fillWithRest)
...
       for (Fraction f2 : qAsConst(flist)) {
             f  -= f2;
+            if (expand) {
+                  if (auto nm = cr1->measure()->nextMeasure()) {
+                        if (auto seg = nm->first(SegmentType::ChordRest)) {
+                              expandVoice(seg, cr1->track());
+                              }
+                        }
+                  }
             makeGap(cr1->segment(), cr1->track(), f2, tuplet, first);
```
Comment (Jojo-Schmitz) [inline libmscore/cmd.cpp:1398]: looks good, this is exactly the place it crashes

Comment (Jojo-Schmitz) [reply libmscore/cmd.cpp:1398]: Any idea why this doesn't seem needed in master?

File: libmscore/cmd.cpp [hunk 2]
```diff
@@ -1386,6 +1388,13 @@ void Score::changeCRlen(ChordRest* cr, const Fraction& dstF, bool fillWithRest)
       bool first = true;
       for (Fraction f2 : qAsConst(flist)) {
```
Comment (Jojo-Schmitz) [inline libmscore/cmd.cpp:1389]: While at it, mind changing this to
```cpp
      for (const Fraction f2 : flist) {
```

**Comment by Jojo-Schmitz** [comment]
Hmm, this seems to bring back the original issue:
image
select the F, press 6
image

**Comment by worldwideweary** [comment]
Hm, okay.. into the next-next measure. Originally it used to happen even without going into the next measure when increasing the duration like this (this is 3.6.2:)

https://github.com/Jojo-Schmitz/MuseScore/assets/7139517/90a0d763-0dea-42a4-91ab-7e1f062e93e3


I'll check it out later tomorrow. I think if I were to just reset the boolean i put in there afterwards, it'd be okay but that's just a quick guess.

**Comment by worldwideweary** [comment]
I threw in a reset of the expand boolean test. Try it out. For me it's sleep time.

**Comment by Jojo-Schmitz** [comment]
Good night!

**Comment by Jojo-Schmitz** [comment]
Yep, that fixes it.
I'd prefer though to have thes first 2 lines of your PR nearer to where they are used, i.e. directly before the for-loop, maybe like this:
```cpp
diff --git a/libmscore/cmd.cpp b/libmscore/cmd.cpp
index 5eb6c9ecff..35eee14b12 100644
--- a/libmscore/cmd.cpp
+++ b/libmscore/cmd.cpp
@@ -1384,8 +1384,17 @@ void Score::changeCRlen(ChordRest* cr, const Fraction& dstF, bool fillWithRest)
       Chord* oc      = 0;

       bool first = true;
+      bool expand = ((cr1->tick() + f) > Fraction(1, 1));
       for (Fraction f2 : qAsConst(flist)) {
             f  -= f2;
+            if (expand) {
+                  if (auto nm = cr1->measure()->nextMeasure()) {
+                        if (auto seg = nm->first(SegmentType::ChordRest)) {
+                              expandVoice(seg, cr1->track());
+                              }
+                        }
+                  expand = false;
+                  }
             makeGap(cr1->segment(), cr1->track(), f2, tuplet, first);

             if (cr->isRest()) {

```

**Comment by worldwideweary** [comment]
Checking in: also creates a rest in later measures instead of the first or so because of using tick() instead of a relative tick, so it exceeds the Frac(1/1) check + can use first instead of unsetting expand

**Comment by Jojo-Schmitz** [comment]
Unfortunately this crashes when prolonging a non-voice 1 note across more than 1 measure, like a quarter on beat four (in 4/4 time sig) to a longa (8) or maxima (9)

**Comment by worldwideweary** [comment]
Damn.

**Comment by Jojo-Schmitz** [comment]
Maybe add the check from https://github.com/Jojo-Schmitz/MuseScore/issues/359#issuecomment-1976071239 ?

**Comment by worldwideweary** [comment]
Looks like the code needs to check for needing expansion on every loop,... which is worse than just verifying an invalid CR...

**Comment by worldwideweary** [comment]
Demonstration: it *should* be okay. Test ? ;)

Uploading screencast.mp4…

File: libmscore/cmd.cpp [hunk 3]
```diff
@@ -1465,7 +1477,8 @@ void Score::changeCRlen(ChordRest* cr, const Fraction& dstF, bool fillWithRest)
             if (m1 == 0)
                   break;
             Segment* s = m1->first(SegmentType::ChordRest);
-            cr1 = toChordRest(s->element(track));
+            if (!(cr1 = toChordRest(s->element(track))))
+                  break;
```
Comment (Jojo-Schmitz) [inline libmscore/cmd.cpp:1481]: Might be worth an assert, like "this shounld't happen, ever"?

**Comment by Jojo-Schmitz** [comment]
Looks good. But how about this:
```cpp
diff --git a/libmscore/cmd.cpp b/libmscore/cmd.cpp
index 5eb6c9ecff..8522c14fa0 100644
--- a/libmscore/cmd.cpp
+++ b/libmscore/cmd.cpp
@@ -1384,8 +1384,17 @@ void Score::changeCRlen(ChordRest* cr, const Fraction& dstF, bool fillWithRest)
       Chord* oc      = 0;

       bool first = true;
+      Fraction totalLen = cr->rtick() + f;
       for (Fraction f2 : qAsConst(flist)) {
             f  -= f2;
+            if (totalLen.reduced() > Fraction(1, 1)) {
+                  if (auto nm = cr1->measure()->nextMeasure()) {
+                        if (auto seg = nm->first(SegmentType::ChordRest)) {
+                              expandVoice(seg, track);
+                              totalLen.setNumerator(totalLen.numerator() - totalLen.denominator());
+                              }
+                        }
+                  }
             makeGap(cr1->segment(), cr1->track(), f2, tuplet, first);

             if (cr->isRest()) {
@@ -1462,10 +1471,12 @@ void Score::changeCRlen(ChordRest* cr, const Fraction& dstF, bool fillWithRest)
                   }
             Measure* m  = cr1->measure();
             Measure* m1 = m->nextMeasure();
-            if (m1 == 0)
+            if (!m1)
                   break;
             Segment* s = m1->first(SegmentType::ChordRest);
             cr1 = toChordRest(s->element(track));
+            if (!cr1)
+                  break;
             }
       connectTies();
       }
```
(not sure about whether to have an assert at the end)

**Comment by worldwideweary** [comment]
I'd leave the assert, but your changes are fine... it's the same thing. Hell, the compiler will probably optimize the stuff anyways to be the exact same anyways.

**Comment by fernandomartin777** [comment]
It's working perfectly now. Thank you.
