### PR TITLE
[Fix] External font loading problem with text cursor accessing unacce…

### LINKED ISSUE #633: Issue/Confirmation: External SMuFL Fonts loading during save sometimes crashes program in peculiar state.
@Jojo-Schmitz have you encountered a crash when saving a score when using externally loaded fonts? It happens to me on occasion when I'm testing some code changes every now and again, and I think I've found the cause. It cracks out on accessing members of a TextCursor. 

```cpp
void ScoreFont::draw(SymId id, QPainter* painter, const QSizeF& mag, const QPointF& pos, qreal worldScale) const
```
In that function, there's an attempt to "addApplicationFont" if the font is null
```diff
+ if (-1 == QFontDatabase::addApplicationFont(s)) {
```
```cpp
if (MScore::pdfPrinting) {
     if (font == 0) {
           QString s(_fontPath+_filename);
           if (-1 == QFontDatabase::addApplicationFont(s)) {
                 qDebug("Mscore: fatal error: cannot load internal font <%s>", qPrintable(s));
                 return;
                 }
```

instead of loading these external fonts into the FontDatabase during app initialization, like in MScore::init(). Apparently that's mostly fine (but seems a shoddy coding practice generally speaking), but on occasion something happens where there's a TextCursor existing and it triggers
```cpp
TextTools::fontChanged()
```
and that checks if a cursor exists. Unfortunately it *does* exist when it seems it shouldn't, and that then continues on 
with:

```cpp
void TextCursor::setFormat(FormatId id, QVariant val)
      {
      changeSelectionFormat(id, val);
      format()->setFormat(id, val);
      text()->setTextInvalid();
      }
```

and that invokes ```changeSelectionFormat``` 

```cpp
void TextCursor::changeSelectionFormat(FormatId id, QVariant val)
      {
      if (!hasSelection())
            return;
      int r1 = selectLine();
      int r2 = row();
      int c1 = selectColumn();
      int c2 = column();
      sort(r1, c1, r2, c2);
```
and the next line is:
```diff
+      int rows = _text->rows();
```

Ahh! `_text->rows()`, but there's no `_text` that has been "prepared" properly, so calling rows() is totally  undefined or inaccessible, and qt library somewhere down the line screws up when accessing the iterator of the container or something of the sort...

### PR DESCRIPTION
**Pull request by worldwideweary**
Resolves: #633 

This time....

### CODE REVIEW

File: libmscore/sym.cpp [hunk 1]
```diff
@@ -6675,6 +6670,17 @@ void ScoreFont::scanUserFonts(const QString& path, bool system)
 
       _allScoreFonts = _builtinScoreFonts;
       _allScoreFonts << _userScoreFonts << _systemScoreFonts;
+
+      // Include external and internal score fonts into QFontDatabase
+      for (auto& f : _allScoreFonts) {
```
Comment (worldwideweary) [inline libmscore/sym.cpp:6675]: Before I was doing _userScoreFonts but now _allScoreFonts because it looked like they were already loaded in there, but they weren't. Only the "text" fonts were loaded in, where I put that comment above

Comment (Jojo-Schmitz) [reply libmscore/sym.cpp:6675]: Does it also fix your original problem?

Comment (worldwideweary) [reply libmscore/sym.cpp:6675]: The code as it was (and is here) hasn't had the crash so far, so I think so. I'll report if I ever experience it again
