### PR TITLE
Fix #554 - Import XML - Verify segment to prevent potential crash

### LINKED ISSUE #554: Musescore 3.7 crash opening xml files
[XML.zip](https://github.com/user-attachments/files/16511268/XML.zip)

Musescore 3.7 crash opening these xml files converted by newzik.com.
They contains errors, but MS 3.6 and 4.X open them without problems.

### PR DESCRIPTION
**Pull request by worldwideweary**
Resolves (hopefully): #554

I tested one of the XML files in the issue. Checked debug output, a bunch of:
```
/importmxmllogger.cpp:Ms::log: Error at line 169 col 10: Non-started tie terminated. No-op.
importmxmllogger.cpp:Ms::log: Error at line 185 col 10: Non-started tie terminated. No-op.
importmxmlpass2.cpp:Ms::convertNotehead: unknown notehead square
importmxmlpass2.cpp:Ms::convertNotehead: unknown notehead square
```

But that doesn't seem the main culprit. Crash on application of a fermata. Notice that the present code assumes a valid chord segment, which probably should be valid, but I think that's where it was crashing. Could be a sign of something worse (why not valid?), but by demanding validity before iterating through annotations or whatever, it should fix the issue.

Needs testing (built locally and verified opening one of the provided xml files, but my local state isn't currently equivalent to 3.7 "evolution")

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
I've just now (literaly 5 minutes ago) switched to MSVC and it's debugger and indeed it crashes on 
```cpp
      for (Element* e: cr->segment()->annotations()) {
```
when trying to work on a Fermata, so your code makes a lot os sense to me

File: importexport/musicxml/importmxmlpass2.cpp [hunk 1]
```diff
@@ -1105,30 +1106,34 @@ static void addFermataToChord(const Notation& notation, ChordRest* cr)
       else
             na->setPlacement(na->propertyDefault(Pid::PLACEMENT).value<Placement>());
       setElementPropertyFlags(na, Pid::PLACEMENT, direction);
-      if (cr->segment() == nullptr && cr->isGrace())
-            cr->el().push_back(na);       // store for later move to segment
+      if (!seg) {
```
Comment (Jojo-Schmitz) [inline importexport/musicxml/importmxmlpass2.cpp:1109]: here I'd prefer
```cpp
      if (!seg == nullptr && cr->isGrace())
            cr->el().push_back(na);       // store for later move to segment
```

File: importexport/musicxml/importmxmlpass2.cpp [hunk 2]
```diff
@@ -1105,30 +1106,34 @@ static void addFermataToChord(const Notation& notation, ChordRest* cr)
...
-                  if (direction.isEmpty() && alreadyAbove)
-                        na->setPlacement(Placement::BELOW);
-                  else if (direction.isEmpty() && alreadyBelow)
-                        na->setPlacement(Placement::ABOVE);
-
-                  if ((otherCr->isChord() && cr->isChord()
-                  && toChord(otherCr)->durationType() == toChord(cr)->durationType())
-                  || (alreadyAbove && alreadyBelow))
-                        na->setVisible(false);
+      if (seg) {
```
Comment (Jojo-Schmitz) [inline importexport/musicxml/importmxmlpass2.cpp:1119]: and here
```cpp
      if (!seg)
            return;
```

File: importexport/musicxml/importmxmlpass2.cpp (hunk 1 above)
Comment (Jojo-Schmitz) [reply importexport/musicxml/importmxmlpass2.cpp:1109]: Won't work though, the entire if/else needs to be skipped?

Comment (worldwideweary) [reply importexport/musicxml/importmxmlpass2.cpp:1109]: what if seg is invalid but is not grace?  then it still attempts to dereference seg in the next line. But i agree about returning on !seg a little later if you'd like

Comment (Jojo-Schmitz) [reply importexport/musicxml/importmxmlpass2.cpp:1109]: Yes, we need to handle seg here twice

Comment (Jojo-Schmitz) [reply importexport/musicxml/importmxmlpass2.cpp:1109]: And may need to loose the `const`

Comment (worldwideweary) [reply importexport/musicxml/importmxmlpass2.cpp]: Looks like const was causing build issues, even though at first seemed like a good idea. Rebased.
(P.S. Lose for drop/remove - "double o seven" loose or loosen for untying a knot :)

File: importexport/musicxml/importmxmlpass2.cpp [hunk 3]
```diff
@@ -1105,15 +1106,18 @@ static void addFermataToChord(const Notation& notation, ChordRest* cr)
...
-      if (cr->segment() == nullptr && cr->isGrace())
+      if (!seg && cr->isGrace())
             cr->el().push_back(na);       // store for later move to segment
-      else
-            cr->segment()->add(na);
+      else if (seg)
+            seg->add(na);
+
+      if (!seg)
+            return;
```
Comment (Jojo-Schmitz) [inline importexport/musicxml/importmxmlpass2.cpp:1115]: Of even
```cpp
      if (!seg && cr->isGrace())
            cr->el().push_back(na);       // store for later move to segment
      else if (seg)
            seg->add(na);
      else
            return;
```

File: importexport/musicxml/importmxmlpass2.cpp (hunk 1 above)
Comment (Jojo-Schmitz) [reply importexport/musicxml/importmxmlpass2.cpp]: Ah, thanks, I never get my head round that difference ;-)

**Comment by Jojo-Schmitz** [comment]
The remaining question is why neither Mu3.6.2 nor Mu4 crash on it, esp. the latter, I might have backported something badly

**Comment by worldwideweary** [comment]
... Yeah, this feels like this is just a safeguard "appendage", but it makes sense for now. Shouldn't hurt anything

**Comment by Jojo-Schmitz** [comment]
Ah, Mu4 doesn't have that`for` loop at all

**Comment by worldwideweary** [comment]
For what it's worth, a 2022! May 27th build of 3.7 still crashes, so the problem is fairly old

**Comment by worldwideweary** [comment]
3.6.2 code reads:

```cpp

static void addFermataToChord(const Notation& notation, ChordRest* cr)
      {
      const SymId articSym = notation.symId();
      const QString direction = notation.attribute("type");
      Fermata* na = new Fermata(articSym, cr->score());
      na->setTrack(cr->track());
      if (!direction.isNull()) // Only for case where XML attribute is present (isEmpty wouldn't work)
            na->setPlacement(direction == "inverted" ? Placement::BELOW : Placement::ABOVE);
      setElementPropertyFlags(na, Pid::PLACEMENT, direction);
      if (cr->segment() == nullptr && cr->isGrace())
            cr->el().push_back(na);       // store for later move to segment
      else
            cr->segment()->add(na);
      }

```

**Comment by Jojo-Schmitz** [comment]
Yep, my port of #8509 for 3.6.2_backend to 3.x

**Comment by worldwideweary** [comment]
Yeah, looks like v.4 code reads like 3.6.2 with the addition of coloring

**Comment by Jojo-Schmitz** [comment]
A MinGW build still crashes on those XML files :-(

**Comment by worldwideweary** [comment]
I'll try to check it out later

**Comment by worldwideweary** [comment]
It's probably the reformed if else stuff...a !seg slips through. Here's another force push:

**Comment by worldwideweary** [comment]
Oh you merged already eh?
